### ISSUE TITLE
Wallet must send token to one of the B to check if this token was ever generated

### ISSUE THREAD

**Issue by mtbitcr** [BitcreditProtocol/Wallet-Core#107]
Wallet send blinded token to random B. B check it in his database. If smth bad - B start rabid process. Wallet never gets back from B anything.

**Comment by zupzup** [comment]
@codingpeanut157 Is this already implemented?

**Comment by codingpeanut157** [comment]
@zupzup 

no
anything related to rabid process or protest have not been implemented

also
I am not sure I understand this task and what exactly "bad" means.
I assume we are in a same-mint scenario, where wallets A and B have the same home-mint.
If wallet B cannot swap the received proofs for new ones due to the mint rejecting the proofs, wallet B has no reason to initiate a rabid process against the mint.
wallet B will simply reject the payment, it's wallet A's responsibility to claim to the mint about those rejected proofs.
The protest process takes long and we can't expect users A and B to wait for such process to happen in order to transfer money.
The best solution is for wallet B to reject the payment, and for wallet A to retry the payment. 
Given that those proofs have been marked as spent in local DB of wallet A, the second attempt will include different proofs. 

If even the 2nd, 3rd, or 4th attempts fail, wallet A has some serious problems, and user A might have to give up and pay in other forms ( or leave the coffe on the counter, or run as fast as he can), but surely wallet B should not be responsible for the issue

**Comment by mtbitcr** [comment]
@codingpeanut157 its about sending token to random beta. I thought we already implemented this. No?

**Comment by codingpeanut157** [comment]
Still not clear what it means, and what B should send to clowder in order to start the rabid process

Maybe @stefanbitcr  can shed some lights here, also, he was the last one implementing new feature in the wallet-core, he certainly knows more

**Comment by mtbitcr** [comment]
@stefanbitcr @codingpeanut157 we currently don't need to implement rabid logic for it. I think @stefanbitcr we speak here about wallet send token to B and B check it in his DB if it was received from A.

**Comment by stefanbitcr** [comment]
I need to add to the Clowder NATs client a function to send a signature, and then Wildcat will have a REST endpoint the wallet can send this signature to, and wilcat sends this via the client.

Something to think about, is whether we can be sure the signature isn't random data without the DLEQ, and was actually signed by Alpha

**Comment by zupzup** [comment]
@stefanbitcr is this already implemented? 🤔

**Comment by stefanbitcr** [comment]
@zupzup It is essentially implemented via the latest Unblinded Verification changes, since a wallet needs to get the proof of issuance for a Swap, it makes the request including proof fingerprints to a Beta which includes the wallet blinding factor and DLEQ, the Beta reblinds it, and if not in the mint stream Beta marks Alpha as rabid. 

Since its mandatory there there isn't a need for the wallet to send the blinded form separately, and without DLEQ the Beta cannot be sure that the blinded signature it hasn't seen was signed by Alpha (wallet forgery)
